### PR TITLE
Ci

### PR DESCRIPTION
**Pull request by LennardBoediger**
add GitHub checks
use external yml file
cleanup

### CODE REVIEW

**Comment by LennardBoediger** [comment]
ready to merge

**Comment by LennardBoediger** [comment]
I have found an edge case issue and will update this soon

**Review by szszszsz — APPROVED** [review]

**Comment by szszszsz** [comment]
I still do not get CI ticks for commits though, see:
- https://github.com/Nitrokey/nitrokey-fido2-firmware/commits/master

**Comment by LennardBoediger** [comment]
fixed

**Pull request closed without merging**
